name: CI

on:
  push:
    branches:
      - main
      - "develop/**"
      - "feature/**"
      - "rescue/**"
  pull_request:

jobs:
  backend:
    name: App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build app container
        run: docker compose build app

      - name: Lint in container
        run: docker compose run --rm --no-deps app make lint

      - name: Check in container
        run: |
          docker compose up -d mongo
          docker compose run --rm app make check

      - name: Docker Compose config
        run: docker compose config

      - name: Validate Dev Container JSON in container
        run: docker compose run --rm --no-deps app python -m json.tool .devcontainer/devcontainer.json >/tmp/devcontainer.json
